on: 
  workflow_dispatch:
  push:
    branches:
      - 'automated-smoke-test'

name: Smoke Test

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    env:
      SCUBA_EXECUTION_CERT_PFX: ${{ secrets.SCUBA_EXECUTION_CERT_PFX }}
      SCUBA_EXECUTION_CERT_PW: ${{ secrets.SCUBA_EXECUTION_CERT_PW }}
    defaults:
          run:
            shell: powershell 
    permissions:
      contents: read 
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Execute ScubaGear and Check Outputs
      run: |
        pwd 
        Get-Location
        . .\Testing\Functional\SmokeTestInit.ps1

        $CertPwd = ConvertTo-SecureString -String "$env:SCUBA_EXECUTION_CERT_PW" -Force -AsPlainText
        New-ServicePrincipalCertificate -EncodedCertificate $env:SCUBA_EXECUTION_CERT_PFX -CertificatePassword $CertPwd

        ##### Install MS Graph and all the dependencies
        #./SetUp.ps1

        ##### Run ScubaGear with a service principal
        #Import-Module -Name ./PowerShell/ScubaGear
        #Invoke-Scuba -CertificateThumbPrint "A9D4870B12F94A344C20BB3FC5774C89F8B5EF33" -AppID "b682d3a5-bc68-450e-80ba-018b97aa2b21" -Organization "cisaent.onmicrosoft.com" -ProductNames "onedrive" -M365Environment "gcc"

        ##### Get the output folder path
        #$ReportFolders = Get-ChildItem . -directory -Filter "M365BaselineConformance*" | Sort-Object -Property LastWriteTime -Descending
        #$OutputFolder = $ReportFolders[0]

        ##### Test that the TestResults.json file is a structurally valid JSON document
        #$JSONContent = Get-Content ".\$OutputFolder\TestResults.json" -Raw | ConvertFrom-Json


        Write-Output "Completed Smoke Test"