on: 
  workflow_dispatch:
  push:
    branches:
      - 'automated-smoke-test'

name: Smoke Test

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    env:
      SCUBA_EXECUTION_CERT_PFX: ${{ secrets.SCUBA_EXECUTION_CERT_PFX }}
      SCUBA_EXECUTION_CERT_PW: ${{ secrets.SCUBA_EXECUTION_CERT_PW }}
    defaults:
          run:
            shell: powershell 
    permissions:
      contents: read 
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Execute ScubaGear and Check Outputs
      run: |
        ##### By default we want the Cmdlets to stop the pipeline when errors occur
        $ErrorActionPreference = "Stop"
        $PSDefaultParameterValues['*:ErrorAction']='Stop'

        ##### Just some debugging info like the branch, Powershell version and current directory
        echo 'Branch: ${{ github.ref }}'
        $PSVersionTable
        pwd

        ##### Get the certificate from GitHub secrets and import it into the local cert store
        Set-Content -Path .\ScubaExecutionCert.txt -Value $env:SCUBA_EXECUTION_CERT_PFX
        certutil -decode .\ScubaExecutionCert.txt .\ScubaExecutionCert.pfx
        $CertPwd = ConvertTo-SecureString -String "$env:SCUBA_EXECUTION_CERT_PW" -Force -AsPlainText
        Import-PfxCertificate -FilePath .\ScubaExecutionCert.pfx -CertStoreLocation Cert:\CurrentUser\My -Password $CertPwd

        ##### Install MS Graph and all the dependencies
        ./SetUp.ps1

        ##### Run ScubaGear with a service principal
        Import-Module -Name ./PowerShell/ScubaGear
        Invoke-Scuba -CertificateThumbPrint "A9D4870B12F94A344C20BB3FC5774C89F8B5EF33" -AppID "b682d3a5-bc68-450e-80ba-018b97aa2b21" -Organization "cisaent.onmicrosoft.com" -ProductNames "onedrive" -M365Environment "gcc"

        ##### Test that the tool created a TestResults.json file
        Test-Path .\TestResults2.json

        ##### Test that the TestResults.json file is a structurally valid JSON document
        $JSONContent = Get-Content .\TestResults.json -Raw | ConvertFrom-Json