on: 
  workflow_dispatch:

name: Smoke Test

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    defaults:
          run:
            shell: powershell 
    permissions:
      contents: write
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Execute ScubaGear
      run: |
        echo 'Branch: ${{ github.ref }}'
        $PSVersionTable


