on: 
  workflow_dispatch:
  push:
    branches:
      - 'automated-smoke-test'

name: Smoke Test

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    defaults:
          run:
            shell: powershell 
    permissions:
      contents: read
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Execute ScubaGear
      run: |
        echo 'Branch: ${{ github.ref }}'
        $PSVersionTable
        ./SetUp.ps1
        Import-Module -Name ./PowerShell/ScubaGear

