on: 
  workflow_dispatch:
  push:
    branches:
      - 'automated-smoke-test'

name: Smoke Test

jobs:
  Run-Smoke-Test:
    runs-on: windows-latest
    env:
      SCUBA_EXECUTION_CERT_PFX: ${{ secrets.SCUBA_EXECUTION_CERT_PFX }}
      SCUBA_EXECUTION_CERT_PW: ${{ secrets.SCUBA_EXECUTION_CERT_PW }}
    defaults:
          run:
            shell: powershell 
    permissions:
      contents: read 
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Execute ScubaGear and Check Outputs
      run: |
        . Testing/Functional/SmokeTest/SmokeTestInit.ps1

        $CertPwd = ConvertTo-SecureString -String "$env:SCUBA_EXECUTION_CERT_PW" -Force -AsPlainText
        $Result = New-ServicePrincipalCertificate -EncodedCertificate $env:SCUBA_EXECUTION_CERT_PFX -CertificatePassword $CertPwd
        $Env:Thumbprint = $Result[-1]
        $Env:Organization = "cisaent.onmicrosoft.com"
        $Env:AppId = "b682d3a5-bc68-450e-80ba-018b97aa2b21"

        ##### Install all the dependencies
        Install-SmokeTestExternalDependencies

        Invoke-Pester -Path Testing/Functional/SmokeTest -Output Detailed

        Write-Output "Completed Smoke Test"